Repository insightsengineering/teal.slice, pull requests merged in 2022-10, with the labels that each got.

#92 As cran
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
  .github/workflows/validate.yaml
  README.md
  inst/WORDLIST
  tests/testthat.R
Labels: enhancement

#110 update NEWS
  NEWS.md
  inst/WORDLIST
Labels: core

#113 fix date filter input
  R/FilterState.R
  inst/css/filter-panel.css
Labels: core

#119 use scda.2022
  DESCRIPTION
  NEWS.md
  staged_dependencies.yaml
Labels: core, Blocked
