Repository insightsengineering/teal.slice, pull requests merged in 2022-07, with the labels that each got.

#60 Fix disappearing Active Filter Datasets
  NEWS.md
  R/FilteredData.R
Labels: core

#66 README and DESCRIPTION
  DESCRIPTION
  README.md
Labels: documentation, core

#65 filterPanelAPI
  NAMESPACE
  R/filter_panel_api.R
  R/filtered_data_wrappers.R
  _pkgdown.yml
  man/FilterPanelAPI.Rd
  tests/testthat/test-filter_panel_api.R
Labels: core

#57 Update FilteredData.R
  NEWS.md
  R/FilteredData.R
Labels: core

#71 add joinkeys into filtered data
  NEWS.md
  R/FilteredData.R
  tests/testthat/test-FilteredData.R
  vignettes/filter-panel.Rmd
Labels: core

#73 683 join keys@main
  R/CDISCFilteredData.R
  R/FilteredData.R
  man/FilteredData.Rd
  tests/testthat/test-FilteredData.R
Labels: core

#80 Update font awesome icon labels for FA 6
  R/FilterStates.R
  R/FilteredData.R
  R/FilteredDataset.R
  man/init_filter_states.Rd
Labels: refactor

#77 Remove FILTERED
  R/CDISCFilteredData.R
  R/FilterStates.R
  R/FilteredData.R
  R/FilteredDataset.R
  R/MAEFilteredDataset.R
  R/utils.R
  man/DefaultFilteredDataset.Rd
  man/FilteredDataset.Rd
  man/MAEFilteredDataset.Rd
  man/check_simple_name.Rd
  man/init_filter_states.Rd
  tests/testthat/test-CDISCFilteredData.R
  tests/testthat/test-DefaultFilteredDataset.R
  tests/testthat/test-FilteredData.R
  tests/testthat/test-FilteredDataset.R
  tests/testthat/test-MAEFilteredDataset.R
  tests/testthat/test-check_simple_name.R
Labels: core

#78 modify get_formatted_filter_state
  R/FilteredData.R
  R/FilteredDataset.R
  man/FilteredDataset.Rd
Labels: core

#79 css review
  R/FilterState.R
  R/FilterStates.R
  R/FilteredData.R
  R/include_css_js.R
  inst/css/filter-panel.css
Labels: core
