Repository insightsengineering/teal.slice, pull requests merged in 2023-12, with the labels that each got.

#490 `tdata` to `teal_data`
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/FilteredData-utils.R
  R/FilteredData.R
  R/FilteredDataset-utils.R
  R/FilteredDataset.R
  R/FilteredDatasetDefault.R
  R/FilteredDatasetMAE.R
  R/filter_panel_api.R
  R/teal_slices.R
  man/DefaultFilteredDataset.Rd
  man/FilteredData.Rd
  man/FilteredDataset.Rd
  man/MAEFilteredDataset.Rd
  man/init_filtered_data.Rd
  man/init_filtered_dataset.Rd
  man/list_to_teal_slices.Rd
  man/validate_dataset_args.Rd
  tests/testthat/test-FilteredData.R
  tests/testthat/test-FilteredDataset.R
  tests/testthat/test-init_filtered_data.R
  vignettes/teal-slice-classes.Rmd
Labels: core, refactor

#495 remove deprecated
  R/FilteredData.R
  man/FilteredData.Rd
Labels: core

#497 493 `FilteredDatasetDefault` class
  NAMESPACE
  NEWS.md
  R/FilteredData.R
  R/FilteredDataset-utils.R
  R/FilteredDatasetDataframe.R
  R/FilteredDatasetDefault.R
  _pkgdown.yml
  man/DataframeFilteredDataset.Rd
  man/DefaultFilteredDataset.Rd
  man/FilteredData.Rd
  man/init_filtered_dataset.Rd
  tests/testthat/test-DataframeFilteredDataset.R
  tests/testthat/test-DefaultFilteredDataset.R
  tests/testthat/test-FilteredData.R
  tests/testthat/test-FilteredDataset.R
  tests/testthat/test-init_filtered_dataset.R
Labels: core

#503 Corrects mapping of parent join_keys columns when merging 2 data frames
  DESCRIPTION
  R/FilteredDatasetDataframe.R
  tests/testthat/test-FilteredData.R
Labels: bug, core
